import Foundation
import VeloxMacros
import VeloxRuntime
import VeloxRuntimeWry

// MARK: - Response Types

struct GreetResponse: Codable, Sendable {
    let message: String
}

struct MathResponse: Codable, Sendable {
    let result: Double
    let operation: String
}

// MARK: - Commands Container

enum Commands {
    @VeloxCommand
    static func greet(name: String) -> GreetResponse {
        GreetResponse(message: "Hello, \(name)!")
    }

    @VeloxCommand
    static func add(a: Double, b: Double) -> MathResponse {
        MathResponse(result: a + b, operation: "addition")
    }

    @VeloxCommand
    static func multiply(a: Double, b: Double) -> MathResponse {
        MathResponse(result: a * b, operation: "multiplication")
    }

    @VeloxCommand
    static func divide(numerator: Double, denominator: Double) throws -> MathResponse {
        guard denominator != 0 else {
            throw CommandError(code: "DivisionByZero", message: "Cannot divide by zero")
        }
        return MathResponse(result: numerator / denominator, operation: "division")
    }
}

// MARK: - Registry using macro-generated commands

let registry = commands {
    Commands.greetCommand      // Generated by @VeloxCommand
    Commands.addCommand        // Generated by @VeloxCommand
    Commands.multiplyCommand   // Generated by @VeloxCommand
    Commands.divideCommand     // Generated by @VeloxCommand
}

// MARK: - Main

func main() {
    let projectDir = URL(fileURLWithPath: #file)
        .deletingLastPathComponent()
        .deletingLastPathComponent()
        .deletingLastPathComponent()

    do {
        let app = try VeloxAppBuilder(directory: projectDir)
            .registerCommands(registry)
        try app.run()
    } catch {
        fatalError("Failed to start app: \(error)")
    }
}

main()
