#include "velox_runtime_wry_ffi.h"

// This translation unit ensures the C target is picked up by SwiftPM while
// leaving all functionality delegated to the Rust static library.
void velox_runtime_wry_ffi_link_helper(void) {
  (void)velox_runtime_wry_library_name;
  (void)velox_runtime_wry_crate_version;
  (void)velox_runtime_wry_webview_version;
  (void)velox_event_loop_new;
  (void)velox_event_loop_free;
  (void)velox_event_loop_pump;
  (void)velox_event_loop_create_proxy;
  (void)velox_event_loop_proxy_request_exit;
  (void)velox_event_loop_proxy_send_user_event;
  (void)velox_event_loop_proxy_free;
  (void)velox_window_build;
  (void)velox_window_free;
  (void)velox_window_identifier;
  (void)velox_window_set_title;
  (void)velox_window_set_fullscreen;
  (void)velox_window_set_decorations;
  (void)velox_window_set_resizable;
  (void)velox_window_set_always_on_top;
  (void)velox_window_set_always_on_bottom;
  (void)velox_window_set_visible_on_all_workspaces;
  (void)velox_window_set_content_protected;
  (void)velox_window_set_visible;
  (void)velox_window_request_redraw;
  (void)velox_window_set_size;
  (void)velox_window_set_position;
  (void)velox_window_set_min_size;
  (void)velox_window_set_max_size;
  (void)velox_window_request_user_attention;
  (void)velox_window_clear_user_attention;
  (void)velox_window_focus;
  (void)velox_window_set_focusable;
  (void)velox_window_set_cursor_grab;
  (void)velox_window_set_cursor_visible;
  (void)velox_window_set_cursor_position;
  (void)velox_window_set_ignore_cursor_events;
  (void)velox_window_start_dragging;
  (void)velox_window_start_resize_dragging;
  (void)velox_webview_build;
  (void)velox_webview_free;
  (void)velox_webview_navigate;
  (void)velox_webview_reload;
  (void)velox_webview_evaluate_script;
  (void)velox_webview_set_zoom;
  (void)velox_webview_show;
  (void)velox_webview_hide;
  (void)velox_webview_clear_browsing_data;
  (void)velox_tray_new;
  (void)velox_tray_free;
  (void)velox_tray_identifier;
  (void)velox_tray_set_title;
  (void)velox_tray_set_tooltip;
  (void)velox_tray_set_visible;
  (void)velox_tray_set_show_menu_on_left_click;
  (void)velox_tray_set_menu;
#if defined(__APPLE__)
  (void)velox_menu_bar_new;
  (void)velox_menu_bar_new_with_id;
  (void)velox_menu_bar_free;
  (void)velox_menu_bar_identifier;
  (void)velox_menu_bar_append_submenu;
  (void)velox_menu_bar_set_app_menu;
  (void)velox_submenu_new;
  (void)velox_submenu_new_with_id;
  (void)velox_submenu_free;
  (void)velox_submenu_identifier;
  (void)velox_submenu_append_item;
  (void)velox_menu_item_new;
  (void)velox_menu_item_free;
  (void)velox_menu_item_set_enabled;
  (void)velox_menu_item_identifier;
#endif
}
